USE [TRAINING_NNET_REPO]
GO

CREATE TABLE [dbo].Test(
	[VendorID] [int] NOT NULL,
	[Name] [nvarchar](128) NULL,
	[Street1] [nvarchar](50) NULL,
	[Street2] [nvarchar](50) NULL,
	[City] [nvarchar](50) NULL
) ON [PRIMARY]
GO

CREATE PROCEDURE [dbo].[SP_DELETE_TABLE_IF_EXISTS] 
	@SCHEMA_NAME nvarchar(20), 
	@TABLE_NAME nvarchar(50) 
 AS
	IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = @SCHEMA_NAME AND TABLE_NAME = @TABLE_NAME)
		BEGIN
		DECLARE @SQL_STATEMENT nvarchar(MAX)
		SET @SQL_STATEMENT = 'DROP TABLE ' + QUOTENAME(@SCHEMA_NAME) + '.' + QUOTENAME(@TABLE_NAME) + ' ';
		EXEC sp_executesql @SQL_STATEMENT;
		PRINT 'TABLE :' + QUOTENAME(@SCHEMA_NAME) + '.' + QUOTENAME(@TABLE_NAME) + ' DELETED'
		END
	ELSE
		BEGIN
			PRINT 'TABLE :' + QUOTENAME(@SCHEMA_NAME) + '.' + QUOTENAME(@TABLE_NAME) + ' DOESNT EXIST IN THIS DATABASE AND SCHEMA'
		END
GO

EXECUTE [dbo].[SP_DELETE_TABLE_IF_EXISTS] @SCHEMA_NAME = N'dbo', @TABLE_NAME = N'Test';